### PR TITLE
Training data fab

### PR DESCRIPTION
**Pull request by FenNlay**

### CODE REVIEW

**Comment by FenNlay** [comment]
@s1nayak

**Comment by FenNlay** [comment]
@Nikav7

**Comment by Nikav7** [comment]
I tried the notebook provided by @FenNlay for training a coqui sst from english samples. The code was easy to follow and I completed the task with success.

**Comment by Nikav7** [comment]
Hence I propose the grade of 10/10 for this code since it was a good start in understanding a simple but effective stt  model training. @FenNlay @s1nayak

**Comment by FenNlay** [comment]
@s1nayak

**Pull request merged**
